import type { JsonSchema, OpenApiDocument } from './document.js';
import { code, jsonBlock, table } from './markdown.js';
import {
  asString,
  componentName,
  constraintsOf,
  describe,
  isObject,
  propertyRows,
  REFINEMENT_KEYS,
  typeName,
} from './reference-schema.js';

/**
 * docs/api-reference.md, rendered from the OpenAPI document the gateway serves at
 * GET /openapi.json (which is itself built from the Zod schemas in packages/schemas).
 *
 * Generated by `pnpm docs:api`; openapi/reference.test.ts fails when the committed file is not
 * byte-identical to a fresh render, the same way packages/schemas guards its json/ directory.
 * docs/api.md stays the HUMAN written contract and is never generated from anything.
 */

/** Rendered in this order when a path item declares several of them. */
export const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete', 'head', 'options'] as const;

export interface ReferenceOperation {
  method: string;
  path: string;
  operation: Record<string, unknown>;
}

/** Every operation of the document, in path order and then in HTTP_METHODS order. */
export const operationsOf = (document: OpenApiDocument): ReferenceOperation[] =>
  Object.entries(document.paths).flatMap(([path, item]) =>
    HTTP_METHODS.filter((method) => isObject(item[method])).map((method) => ({
      method,
      path,
      operation: item[method] as Record<string, unknown>,
    })),
  );

/** docs/api.md gives every route the same bearer scheme, so this is a yes/no. */
export const authOf = (operation: Record<string, unknown>): string =>
  Array.isArray(operation['security']) && operation['security'].length > 0
    ? 'Bearer API key'
    : 'public';

const summaryOf = (operation: Record<string, unknown>): string =>
  asString(operation['summary']) ?? '';

const parameterRows = (operation: Record<string, unknown>): string[][] =>
  (Array.isArray(operation['parameters']) ? operation['parameters'] : [])
    .filter(isObject)
    .map((parameter) => [
      code(asString(parameter['name']) ?? ''),
      asString(parameter['in']) ?? '',
      parameter['required'] === true ? 'yes' : 'no',
      code(typeName(parameter['schema'])),
      describe(parameter, constraintsOf(parameter['schema'])),
    ]);

/** The schema of the first media type of a request or response body, or null when there is none. */
const bodySchema = (holder: Record<string, unknown>): unknown => {
  const content = holder['content'];
  if (!isObject(content)) {
    return null;
  }
  const first = Object.entries(content).find(([, media]) => isObject(media));
  return first === undefined ? null : (first[1] as Record<string, unknown>)['schema'];
};

/** That body as one table cell: the schema name, and the media type when it is not JSON. */
const bodyType = (holder: Record<string, unknown>): string | null => {
  const content = holder['content'];
  if (!isObject(content)) {
    return null;
  }
  const first = Object.keys(content)[0];
  if (first === undefined) {
    return null;
  }
  const name = code(typeName(bodySchema(holder)));
  return first === 'application/json' ? name : `${name} (${first})`;
};

const responseRows = (operation: Record<string, unknown>): string[][] => {
  const responses = operation['responses'];
  if (!isObject(responses)) {
    return [];
  }
  return Object.entries(responses)
    .filter(([, response]) => isObject(response))
    .map(([status, value]) => {
      const response = value as Record<string, unknown>;
      const headers = isObject(response['headers']) ? Object.keys(response['headers']) : [];
      return [
        code(status),
        asString(response['description']) ?? '',
        bodyType(response) ?? 'no body',
        headers.length === 0 ? '—' : headers.map(code).join(', '),
      ];
    });
};

/** The refinements zod carries into JSON Schema that a property table cannot show. */
const refinementBlock = (schema: JsonSchema | undefined): string[] =>
  REFINEMENT_KEYS.flatMap((key) =>
    schema?.[key] === undefined
      ? []
      : [
          '',
          `Additional constraints (${code(key)}), which the property table cannot express:`,
          '',
          ...jsonBlock(schema[key]),
        ],
  );

const requestSection = (
  operation: Record<string, unknown>,
  schemas: Record<string, JsonSchema>,
): string[] => {
  const body = operation['requestBody'];
  if (!isObject(body)) {
    return [];
  }
  const type = bodyType(body);
  if (type === null) {
    return [];
  }
  const required = body['required'] === true ? 'required' : 'optional';
  const lines = ['', `**Request body** (${required}): ${type}`, ''];
  const name = componentName(bodySchema(body));
  const schema = name === null ? undefined : schemas[name];
  const rows = propertyRows(schema);
  if (rows.length > 0) {
    lines.push(...table(['Field', 'Type', 'Required', 'Notes'], rows));
  }
  lines.push(...refinementBlock(schema));
  return lines;
};

const operationSection = (
  { method, path, operation }: ReferenceOperation,
  schemas: Record<string, JsonSchema>,
): string[] => {
  const lines = ['', `### ${method.toUpperCase()} ${path}`, ''];
  const summary = summaryOf(operation);
  if (summary !== '') {
    lines.push(summary, '');
  }
  const description = asString(operation['description']);
  if (description !== null) {
    lines.push(description, '');
  }
  lines.push(`Auth: ${authOf(operation)}.`);
  const parameters = parameterRows(operation);
  if (parameters.length > 0) {
    lines.push(
      '',
      '**Parameters**',
      '',
      ...table(['Name', 'In', 'Required', 'Type', 'Notes'], parameters),
    );
  }
  lines.push(...requestSection(operation, schemas));
  const responses = responseRows(operation);
  if (responses.length > 0) {
    lines.push(
      '',
      '**Responses**',
      '',
      ...table(['Status', 'Meaning', 'Body', 'Headers'], responses),
    );
  }
  return lines;
};

const header = (document: OpenApiDocument): string[] => [
  '<!-- Generated from the OpenAPI document by `pnpm docs:api`. Do not edit by hand:',
  '     packages/gateway/src/openapi/reference.test.ts compares this file with a fresh render. -->',
  '',
  `# ${document.info.title} API reference`,
  '',
  document.info.description,
  '',
  '**[docs/api.md](api.md) is the contract.** It is written by hand and changes only by a human',
  'decision. This file is generated from the OpenAPI document the gateway serves at',
  `${code('GET /openapi.json')}, which is built from the Zod schemas in ${code('packages/schemas')}.`,
  'Where the two disagree, docs/api.md is right and the code is wrong.',
  '',
  ...table(
    ['', ''],
    [
      ['API version', code(document.info.version)],
      ['OpenAPI', code(document.openapi)],
      ['JSON Schema dialect', code(document.jsonSchemaDialect)],
      ['Licence', code(document.info.license.name)],
      ['Regenerate', code('pnpm docs:api')],
    ],
  ),
];

const authSection = (document: OpenApiDocument): string[] => [
  '',
  '## Authentication',
  '',
  ...Object.entries(document.components.securitySchemes).map(([name, scheme]) => {
    const kind = [asString(scheme['type']), asString(scheme['scheme'])]
      .filter((part): part is string => part !== null)
      .join(' ');
    return `- ${code(name)} (${kind}): ${asString(scheme['description']) ?? ''}`.trimEnd();
  }),
];

/** The whole of docs/api-reference.md, ending in a newline. */
export const renderApiReference = (document: OpenApiDocument): string => {
  const operations = operationsOf(document);
  const schemas = document.components.schemas;
  const lines = [
    ...header(document),
    ...authSection(document),
    '',
    '## Endpoints',
    '',
    ...table(
      ['Method', 'Path', 'Auth', 'Summary'],
      operations.map(({ method, path, operation }) => [
        method.toUpperCase(),
        code(path),
        authOf(operation),
        summaryOf(operation),
      ]),
    ),
    ...operations.flatMap((entry) => operationSection(entry, schemas)),
    '',
    '## Schemas',
    '',
    `Every schema below is a component of ${code('GET /openapi.json')} and is also written to`,
    `${code('packages/schemas/json/<Name>.schema.json')} (JSON Schema 2020-12).`,
    '',
    ...table(
      ['Name', 'Description'],
      Object.entries(schemas).map(([name, schema]) => [code(name), describe(schema)]),
    ),
  ];
  return `${lines.join('\n')}\n`;
};
