import { apps, reports } from '@adgate/gateway/schema';
import { eq, type SQL } from 'drizzle-orm';

import { type AppScope, scopeOwnerId } from './app-scope';
import { type DashboardDb, dashboardDb } from './db';

/**
 * The SQL half of lib/app-scope.ts: the two predicates every scoped read is built out of, plus
 * the two by-id checks the detail pages use.
 *
 * WHY IT IS A PREDICATE ON `apps` AND NOT ON EACH TABLE. `apps.owner_user_id` is the only
 * ownership column that matters: creatives point at an app, audit records point at an app, and
 * the audit and metrics queries already reach audit_records through `apps` (a CROSS JOIN LATERAL
 * per app - see lib/audit-queries.ts and lib/metrics-queries.ts), so adding one `where` on the
 * outer `apps` scan scopes them all without changing a single plan. `reports` is the exception
 * and carries its own owner column, because a report is generated by an account and covers only
 * that account's apps.
 *
 * WHERE A FUTURE QUERY COULD STILL BYPASS THIS: any new SELECT that reaches audit_records,
 * creatives or events WITHOUT going through `apps` (or through one of the helpers below) is
 * unscoped by construction. lib/scope-coverage.test.ts fails when a query module stops
 * mentioning an AppScope, which is the tripwire for exactly that mistake.
 */

/**
 * `apps.owner_user_id = <member>` for a member; undefined for an admin, which drizzle's `and()`
 * drops, leaving the query byte-identical to the one this dashboard ran before accounts existed.
 * That is deliberate: the EXPLAIN suite plans the ADMIN shape, and an admin's plan must not
 * change because members exist.
 */
export const appScopeCondition = (scope: AppScope): SQL | undefined => {
  const owner = scopeOwnerId(scope);
  return owner === null ? undefined : eq(apps.ownerUserId, owner);
};

/** The same predicate for the `reports` table's own owner column. */
export const reportScopeCondition = (scope: AppScope): SQL | undefined => {
  const owner = scopeOwnerId(scope);
  return owner === null ? undefined : eq(reports.ownerUserId, owner);
};

/**
 * Whether this scope may read the app with that id. An admin may read any app that exists; a
 * member may read only their own, and gets the same `false` for an app that belongs to somebody
 * else as for an app id that was never registered - which is what keeps a detail page from being
 * an existence oracle.
 */
export const appIsVisible = async (
  scope: AppScope,
  appId: string,
  db: DashboardDb = dashboardDb(),
): Promise<boolean> => {
  const owner = scopeOwnerId(scope);
  const [row] = await db
    .select({ ownerUserId: apps.ownerUserId })
    .from(apps)
    .where(eq(apps.id, appId))
    .limit(1);
  if (row === undefined) {
    return false;
  }
  return owner === null || row.ownerUserId === owner;
};

/**
 * The app ids this scope may see, for the one place a predicate on `apps` is not enough: the
 * report record range, which starts from `audit_records.advertiser_id` and has no `apps` scan to
 * hang a condition on. Returns null for an admin, meaning "no restriction" - so the admin query
 * keeps the exact shape the EXPLAIN test plans.
 *
 * The list is small (an operator's apps, or one developer's), and resolving it in JavaScript
 * rather than as an `IN (subquery)` keeps `audit_records_advertiser_id_ts_idx` as the index
 * condition of the range scan instead of turning it into a semi-join.
 */
export const visibleAppIds = async (
  scope: AppScope,
  db: DashboardDb = dashboardDb(),
): Promise<string[] | null> => {
  const condition = appScopeCondition(scope);
  if (condition === undefined) {
    return null;
  }
  const rows = await db.select({ id: apps.id }).from(apps).where(condition);
  return rows.map((row) => row.id);
};
